deidentify_tags = [
    "StudyDate",
    "SeriesDate",
    "AcquisitionDate",
    "ContentDate",
    "OverlayDate",
    "CurveDate",
    "AcquisitionDateTime",
    "StudyTime",
    "SeriesTime",
    "AcquisitionTime",
    "ContentTime",
    "OverlayTime",
    "CurveTime",
    "AccessionNumber",
    "InstitutionName",
    "InstitutionAddress",
    "ReferringPhysiciansName",
    "ReferringPhysicianName", 
    "ReferringPhysiciansAddress",
    "ReferringPhysicianAddress", 
    "ReferringPhysiciansTelephoneNumber",
    "ReferringPhysicianTelephoneNumber", 
    "ReferringPhysicianIDSequence",
    "InstitutionalDepartmentName",
    "PhysicianOfRecord",
    "PhysicianOfRecordIDSequence",
    "PerformingPhysiciansName",
    "PerformingPhysicianName", 
    "PerformingPhysicianIDSequence",
    "NameOfPhysicianReadingStudy",
    "PhysicianReadingStudyIDSequence",
    "OperatorsName",
    "OperatorName",
    "PatientName", 
    "PatientsName",
    "PatientID",
    "IssuerOfPatientID",
    "PatientBirthDate",
    "PatientsBirthDate",
    "PatientBirthTime", 
    "PatientsBirthTime",
    "PatientSex", 
    "PatientsSex",
    "OtherPatientID", 
    "OtherPatientIDs",
    "OtherPatientName", 
    "OtherPatientNames",
    "PatientBirthName", 
    "PatientsBirthName",
    "PatientAge", 
    "PatientsAge",
    "PatientAddress",
    "PatientsAddress",
    "PatientMotherBirthName", 
    "PatientsMothersBirthName",
    "CountryOfResidence",
    "RegionOfResidence",
    "PatientsTelephoneNumbers",
    "StudyID",
    "CurrentPatientLocation",
    "PatientsInstitutionResidence",
    "DateTime",
    "Date",
    "Time",
    "PersonName"
]

def deidentify(header_info):
    for item in header_info:
        if item["Attribute Name"] in deidentify_tags:
            item["Value"] = 'De-identified'
    return header_info